import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { Plus, BarChart2, Settings, ExternalLink, Trash2, Edit, Copy } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { useSubscription } from '../hooks/useSubscription'
import { supabase } from '../lib/supabase'
import AnalyticsDashboard from '../components/AnalyticsDashboard'
import EmbedCodeGenerator from '../components/EmbedCodeGenerator'
import SubscriptionBadge from '../components/SubscriptionBadge'

function Dashboard() {
  const { user } = useAuth()
  const { currentPlan, hasAccess } = useSubscription()
  const [calculators, setCalculators] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [activeTab, setActiveTab] = useState('calculators') // 'calculators', 'analytics', 'settings'
  const [selectedCalculator, setSelectedCalculator] = useState(null)

  // Fetch user's calculators
  useEffect(() => {
    const fetchCalculators = async () => {
      try {
        setLoading(true)
        setError(null)
        
        const { data, error } = await supabase
          .from('calculators')
          .select('*')
          .eq('userId', user.id)
          .order('createdAt', { ascending: false })
        
        if (error) throw error
        
        setCalculators(data || [])
        
        // Set first calculator as selected if available
        if (data && data.length > 0 && !selectedCalculator) {
          setSelectedCalculator(data[0])
        }
      } catch (err) {
        console.error('Error fetching calculators:', err)
        setError('Failed to load calculators. Please try again.')
      } finally {
        setLoading(false)
      }
    }
    
    if (user) {
      fetchCalculators()
    }
  }, [user, selectedCalculator])

  const handleDeleteCalculator = async (calculatorId) => {
    if (!confirm('Are you sure you want to delete this calculator? This action cannot be undone.')) {
      return
    }
    
    try {
      setLoading(true)
      
      const { error } = await supabase
        .from('calculators')
        .delete()
        .eq('calculatorId', calculatorId)
      
      if (error) throw error
      
      // Update calculators list
      setCalculators(calculators.filter(calc => calc.calculatorId !== calculatorId))
      
      // Clear selected calculator if it was deleted
      if (selectedCalculator && selectedCalculator.calculatorId === calculatorId) {
        setSelectedCalculator(null)
      }
    } catch (err) {
      console.error('Error deleting calculator:', err)
      setError('Failed to delete calculator. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const handleDuplicateCalculator = async (calculator) => {
    try {
      setLoading(true)
      
      // Create a copy of the calculator
      const newCalculator = {
        ...calculator,
        calculatorId: undefined, // Will be generated by Supabase
        name: `${calculator.name} (Copy)`,
        createdAt: new Date().toISOString()
      }
      
      const { data, error } = await supabase
        .from('calculators')
        .insert([newCalculator])
        .select()
      
      if (error) throw error
      
      // Update calculators list
      setCalculators([...calculators, data[0]])
      
      // Set the new calculator as selected
      setSelectedCalculator(data[0])
    } catch (err) {
      console.error('Error duplicating calculator:', err)
      setError('Failed to duplicate calculator. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  // Check if user has reached calculator limit
  const calculatorLimit = currentPlan.limits.calculators
  const hasReachedLimit = calculators.length >= calculatorLimit && calculatorLimit !== Infinity

  return (
    <div className="min-h-screen bg-bg">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-text-primary">Dashboard</h1>
            <p className="text-text-secondary">
              Manage your calculators and view analytics
            </p>
          </div>
          
          <div className="flex items-center space-x-4">
            <SubscriptionBadge />
            
            <Link
              to="/create"
              className={`btn-primary flex items-center space-x-2 ${
                hasReachedLimit ? 'opacity-50 cursor-not-allowed' : ''
              }`}
              onClick={(e) => {
                if (hasReachedLimit) {
                  e.preventDefault()
                  alert(`You've reached the limit of ${calculatorLimit} calculators on your current plan. Please upgrade to create more.`)
                }
              }}
            >
              <Plus className="h-4 w-4" />
              <span>New Calculator</span>
            </Link>
          </div>
        </div>

        {/* Dashboard Tabs */}
        <div className="mb-6">
          <div className="flex border-b border-gray-200">
            <button
              onClick={() => setActiveTab('calculators')}
              className={`px-4 py-2 font-medium text-sm flex items-center ${
                activeTab === 'calculators'
                  ? 'text-primary border-b-2 border-primary'
                  : 'text-text-secondary hover:text-text-primary'
              }`}
            >
              My Calculators
            </button>
            <button
              onClick={() => setActiveTab('analytics')}
              className={`px-4 py-2 font-medium text-sm flex items-center ${
                activeTab === 'analytics'
                  ? 'text-primary border-b-2 border-primary'
                  : 'text-text-secondary hover:text-text-primary'
              }`}
            >
              <BarChart2 className="h-4 w-4 mr-2" />
              Analytics
            </button>
            <button
              onClick={() => setActiveTab('embed')}
              className={`px-4 py-2 font-medium text-sm flex items-center ${
                activeTab === 'embed'
                  ? 'text-primary border-b-2 border-primary'
                  : 'text-text-secondary hover:text-text-primary'
              }`}
            >
              <ExternalLink className="h-4 w-4 mr-2" />
              Embed
            </button>
            <button
              onClick={() => setActiveTab('settings')}
              className={`px-4 py-2 font-medium text-sm flex items-center ${
                activeTab === 'settings'
                  ? 'text-primary border-b-2 border-primary'
                  : 'text-text-secondary hover:text-text-primary'
              }`}
            >
              <Settings className="h-4 w-4 mr-2" />
              Settings
            </button>
          </div>
        </div>

        {/* Calculators Tab */}
        {activeTab === 'calculators' && (
          <div>
            {loading && calculators.length === 0 ? (
              <div className="text-center py-12">
                <div className="inline-block h-8 w-8 border-4 border-primary/20 border-t-primary rounded-full animate-spin mb-4"></div>
                <p className="text-text-secondary">Loading calculators...</p>
              </div>
            ) : error ? (
              <div className="text-center py-12">
                <p className="text-red-600 mb-4">{error}</p>
                <button
                  onClick={() => window.location.reload()}
                  className="btn-secondary"
                >
                  Retry
                </button>
              </div>
            ) : calculators.length === 0 ? (
              <div className="text-center py-12 bg-white rounded-lg shadow-sm">
                <Settings className="h-16 w-16 text-gray-300 mx-auto mb-4" />
                <h2 className="text-xl font-medium text-text-primary mb-2">No calculators yet</h2>
                <p className="text-text-secondary mb-6 max-w-md mx-auto">
                  Create your first calculator to get started. You can build custom calculators for your website or application.
                </p>
                <Link to="/create" className="btn-primary">
                  Create Your First Calculator
                </Link>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {calculators.map((calculator) => (
                  <div key={calculator.calculatorId} className="card p-6">
                    <div className="flex justify-between items-start mb-4">
                      <h3 className="text-lg font-semibold text-text-primary">{calculator.name}</h3>
                      <div className="flex space-x-1">
                        <button
                          onClick={() => handleDuplicateCalculator(calculator)}
                          className="p-1 text-text-secondary hover:text-text-primary transition-colors"
                          title="Duplicate"
                        >
                          <Copy className="h-4 w-4" />
                        </button>
                        <Link
                          to={`/edit/${calculator.calculatorId}`}
                          className="p-1 text-text-secondary hover:text-text-primary transition-colors"
                          title="Edit"
                        >
                          <Edit className="h-4 w-4" />
                        </Link>
                        <button
                          onClick={() => handleDeleteCalculator(calculator.calculatorId)}
                          className="p-1 text-text-secondary hover:text-red-600 transition-colors"
                          title="Delete"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </div>
                    
                    <p className="text-text-secondary text-sm mb-4 line-clamp-2">
                      {calculator.description || 'No description'}
                    </p>
                    
                    <div className="flex justify-between items-center">
                      <div className="text-xs text-text-secondary">
                        Created: {new Date(calculator.createdAt).toLocaleDateString()}
                      </div>
                      
                      <Link
                        to={`/preview/${calculator.calculatorId}`}
                        className="text-primary hover:text-primary/80 text-sm font-medium flex items-center"
                      >
                        <ExternalLink className="h-3 w-3 mr-1" />
                        Preview
                      </Link>
                    </div>
                  </div>
                ))}
              </div>
            )}
            
            {/* Calculator Limit Indicator */}
            {calculatorLimit !== Infinity && (
              <div className="mt-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
                <div className="flex justify-between items-center">
                  <div>
                    <p className="text-sm text-text-secondary">
                      Calculator Usage: <span className="font-medium">{calculators.length} / {calculatorLimit}</span>
                    </p>
                    <div className="w-48 h-2 bg-gray-200 rounded-full mt-2">
                      <div 
                        className="h-2 bg-primary rounded-full" 
                        style={{ width: `${(calculators.length / calculatorLimit) * 100}%` }}
                      ></div>
                    </div>
                  </div>
                  
                  {hasReachedLimit && (
                    <Link to="/pricing" className="btn-primary text-sm">
                      Upgrade Plan
                    </Link>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Analytics Tab */}
        {activeTab === 'analytics' && (
          <div>
            {calculators.length === 0 ? (
              <div className="text-center py-12 bg-white rounded-lg shadow-sm">
                <BarChart2 className="h-16 w-16 text-gray-300 mx-auto mb-4" />
                <h2 className="text-xl font-medium text-text-primary mb-2">No analytics available</h2>
                <p className="text-text-secondary mb-6 max-w-md mx-auto">
                  Create your first calculator to start collecting analytics data.
                </p>
                <Link to="/create" className="btn-primary">
                  Create Calculator
                </Link>
              </div>
            ) : (
              <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                <div className="lg:col-span-1">
                  <div className="card p-4">
                    <h3 className="text-lg font-semibold text-text-primary mb-4">
                      Select Calculator
                    </h3>
                    <div className="space-y-2">
                      {calculators.map((calculator) => (
                        <button
                          key={calculator.calculatorId}
                          onClick={() => setSelectedCalculator(calculator)}
                          className={`w-full text-left p-3 rounded-md ${
                            selectedCalculator?.calculatorId === calculator.calculatorId
                              ? 'bg-primary/10 text-primary'
                              : 'hover:bg-gray-50 text-text-primary'
                          }`}
                        >
                          {calculator.name}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
                
                <div className="lg:col-span-3">
                  <AnalyticsDashboard calculator={selectedCalculator} />
                </div>
              </div>
            )}
          </div>
        )}

        {/* Embed Tab */}
        {activeTab === 'embed' && (
          <div>
            {calculators.length === 0 ? (
              <div className="text-center py-12 bg-white rounded-lg shadow-sm">
                <ExternalLink className="h-16 w-16 text-gray-300 mx-auto mb-4" />
                <h2 className="text-xl font-medium text-text-primary mb-2">No calculators to embed</h2>
                <p className="text-text-secondary mb-6 max-w-md mx-auto">
                  Create your first calculator to get embed code.
                </p>
                <Link to="/create" className="btn-primary">
                  Create Calculator
                </Link>
              </div>
            ) : (
              <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                <div className="lg:col-span-1">
                  <div className="card p-4">
                    <h3 className="text-lg font-semibold text-text-primary mb-4">
                      Select Calculator
                    </h3>
                    <div className="space-y-2">
                      {calculators.map((calculator) => (
                        <button
                          key={calculator.calculatorId}
                          onClick={() => setSelectedCalculator(calculator)}
                          className={`w-full text-left p-3 rounded-md ${
                            selectedCalculator?.calculatorId === calculator.calculatorId
                              ? 'bg-primary/10 text-primary'
                              : 'hover:bg-gray-50 text-text-primary'
                          }`}
                        >
                          {calculator.name}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
                
                <div className="lg:col-span-3">
                  {selectedCalculator ? (
                    <EmbedCodeGenerator calculator={selectedCalculator} />
                  ) : (
                    <div className="text-center py-12 bg-white rounded-lg shadow-sm">
                      <p className="text-text-secondary">
                        Select a calculator to get embed code
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Settings Tab */}
        {activeTab === 'settings' && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2">
              <div className="card p-6">
                <h3 className="text-lg font-semibold text-text-primary mb-6">
                  Account Settings
                </h3>
                
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium text-text-primary mb-2">
                      Email Address
                    </label>
                    <input
                      type="email"
                      value={user?.email || ''}
                      disabled
                      className="input-field bg-gray-50"
                    />
                    <p className="text-xs text-text-secondary mt-1">
                      Your account email address
                    </p>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-text-primary mb-2">
                      Current Plan
                    </label>
                    <div className="flex items-center space-x-2">
                      <SubscriptionBadge showLabel={true} />
                      <Link to="/pricing" className="text-primary hover:text-primary/80 text-sm">
                        Change Plan
                      </Link>
                    </div>
                  </div>
                  
                  <div className="pt-4 border-t border-gray-200">
                    <h4 className="font-medium text-text-primary mb-2">
                      Danger Zone
                    </h4>
                    <button
                      onClick={() => {
                        if (confirm('Are you sure you want to delete your account? This action cannot be undone.')) {
                          // Delete account logic
                        }
                      }}
                      className="text-red-600 hover:text-red-800 text-sm font-medium"
                    >
                      Delete Account
                    </button>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="lg:col-span-1">
              <div className="card p-6">
                <h3 className="text-lg font-semibold text-text-primary mb-4">
                  Plan Details
                </h3>
                
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium text-text-primary">
                      {currentPlan.name} Plan
                    </h4>
                    <p className="text-text-secondary text-sm">
                      ${currentPlan.price}/month
                    </p>
                  </div>
                  
                  <div className="pt-4 border-t border-gray-200">
                    <h4 className="font-medium text-text-primary mb-2">
                      Features
                    </h4>
                    <ul className="space-y-2">
                      {currentPlan.features.map((feature, index) => (
                        <li key={index} className="flex items-start text-sm">
                          <span className="text-accent mr-2">✓</span>
                          <span className="text-text-secondary">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  
                  <div className="pt-4">
                    <Link to="/pricing" className="btn-primary w-full text-center">
                      {currentPlan.id === 'free' ? 'Upgrade Plan' : 'Manage Subscription'}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default Dashboard

